### ISSUE TITLE
Strip :80 from calendar feed URL

### ISSUE THREAD

**Issue by Aupajo** [Aupajo/almanack#14]

**Comment by steveb85** [comment]
Any update on this? Even when i pull the port number from the URL Icalendar is throwing an error that stops it from subscribing? Google calendar doesn't throw errors, but doesn't take any of the events.

**Comment by Aupajo** [comment]
@steveb85 I've fixed the feed URL incorporating `:80` and `:443` in 1.1.2, which fixes this issue. You can upgrade with:

    cd my-almanack-calendar
    bundle update almanack

However, I don't believe the presence or absence of port numbers would affect any behaviour in the macOS Calendar app or Google Calendar. Perhaps there's a different issue at play. What steps can I take to recreate your issue?
