### ISSUE TITLE
Meetup API throttling

### ISSUE THREAD

**Issue by popey** [Aupajo/almanack#17]
I've added a bunch (possibly too many?) meetup events to my config.ru. I'm getting throttled by the meetup api, and their advice is to simply add a pause between one call and the next. Perhaps this is something that could be done in almanack? Otherwise I guess I just have to reduce the number of meetups I'm following?

**Comment by Aupajo** [comment]
@popey What I've done is use multiple API keys and just cycle them:

```
Almanack.config do |c|
  %w( MEETUP_KEY_1 MEETUP_KEY_2 MEETUP_KEY_3 ).cycle do |api_key|
    c.add_meetup_group(group_urlname: 'WikiHouse-NZ', meetup_api_key: api_key)
  end
end
```

Hope that helps!

**Comment by benblaine** [comment]
Firstly: great to see a solution! I'm struggling to get it to work.

I have 3 keys. When I try to run this I get "You're not authorised to make this request."

I've tried each key individually and they each work. 


This isan example of my code...

```
Almanack.config do |c|
  c.title = "Events Calendar"
  c.theme = "legacy" # available: legacy
  c.days_lookahead = 30

  meetup_keys = %w( MEETUP_KEY1 MEETUP_KEY2 MEETUP_KEY3 ).cycle

  c.add_meetup_group group_urlname: 'ctfeds', key: 'meetup_keys.next'
  c.add_meetup_group group_urlname: 'cape-town-js', key: 'meetup_keys.next'
  c.add_meetup_group group_urlname: 'Cape-Town-Data-Science-Meetup', key: 'meetup_keys.next'

end

run Almanack::Server
```

**Comment by Aupajo** [comment]
The combination of caching and multiple API keys works well.

```ruby
Almanack.config do |c|
  # Don't fetch event information more than once every 15 minutes
  c.cache_responses = true
  c.cache_expiry = ENV.fetch('CACHE_DURATION_IN_SECONDS') { 900 }.to_i

  meetup_keys = %w( MEETUP_KEY_1 MEETUP_KEY_2 ).cycle
  meetup_groups = %w(
    WikiHouse-NZ
    CHC-JS
    ISIG-Christchurch-NZ
    Design-Thinking-Group
  )

  meetup_groups.each do |group|
    c.add_meetup_group(group_urlname: group, meetup_api_key: meetup_keys.next
  end
end
```
